### ISSUE TITLE
Accessing sites with alert to follow location block further html webpages

### ISSUE THREAD

**Issue by wnm3** [IBM/MDfromHTML#20]
We get a timeout after accessing a web page that raises an alert box asking to allow or block access to location. Some examples of these pages are listed below:

http://www.foxtel.com.au/now/support
https://www.foxtel.com.au/about/contact.html
https://www.foxtel.com.au/channel-packs/foxtel-plus.html
https://www.foxtel.com.au/channel-packs/foxtel-plus.html?icid=resi_channel-pack-landing-page_cta_learn-more
https://www.foxtel.com.au/login/forgot/forgot-password-email-check.html
https://www.foxtel.com.au/now/login/forgot-password.html
https://www.foxtel.com.au/now/support.html
https://www.foxtel.com.au/now/support/manage-my-account/cancel.html
https://www.foxtel.com.au/shop/bundles/no-contract/sports-hd.html
https://www.foxtel.com.au/shop/upgrade/multiroom.html
https://www.foxtel.com.au/support/accounts-billing/equipment/return/no-return-required.html
https://www.foxtel.com.au/support/accounts-billing/equipment/return/return-equipment.html
https://www.foxtel.com.au/support/products-and-features/cast-foxtel-go.html
https://www.foxtel.com.au/support/products-and-features/multiroom.html#aboutmultiscreen
https://www.foxtel.com.au/support/products-and-features/remotes-and-accessories.html
https://www.foxtel.com.au/support/products-and-features/using-my-iq4.html#faq-item-2-col-n1-faqaccordion
https://www.foxtel.com.au/support/technical-support/error-code-troubleshooting/iq4/f0704.html
https://www.foxtel.com.au/support/technical-support/free-to-air-troubleshooting/missing-channels/iq3.html
https://www.foxtel.com.au/support/tv/how-to-use/tv-guide-recording/recording-tips.html#:~:text=Your iQ4 and iQ3 can record up to 3 shows,or watching a 4th live

One can use the UX webpage to retrieve most of them individually, but attempting a 2nd URL afterwards will time out. This also occurs with issuing requests via cURL commands.

These pages fail to complete due to an outstanding request (though there is sufficient HTML received to save it).
https://www.foxtel.com.au/login/forgot/forgot-password-email-check.html
https://www.foxtel.com.au/now/support.html

**Comment by wnm3** [comment]
@sivasankalpp perhaps when starting the chromium browser there is a way to block the location request via a setting? https://perishablepress.com/disable-location-prompts-google-chrome/ shows how people manually can disable these prompts. A person could do this manually after starting htmlcapture.py but before kicking off the script to request page captures. I don't know after a timeout if chromium is restarted and therefore we'd lose this setting if set manually.

**Comment by sivasankalpp** [comment]
@wnm3 Thanks for the description! Sorry I missed this earlier. 

We could add these lines after https://github.com/IBM/MDfromHTML/blob/6bab2873867b9ff70c81dd55da88550715f1c82c/html_extractor/webapp/content.py#L50
```
prefs = {"profile.default_content_setting_values.geolocation" :2}
options.add_experimental_option("prefs",prefs)
```
Ref: https://stackoverflow.com/a/40245160, https://stackoverflow.com/a/66326777

I haven't tested this yet, but definitely worth trying for a quick fix.
